# site properties and page defaults
title: METU SPARG
subtitle: METU Spatial Audio Research Group
show-title: false
description: >-
  Founded in 2013 to consolidate ongoing research work at METU Graduate School of Informatics 
  in the area of audio signal processing to further the state-of-the-art in 
  spatial and 3D audio capture, editing, synthesis, transmission, reproduction, and testing.
header: images/lab_zylias.jpg
footer: images/lab_zylias.jpg
proofer: false

# site social media and other links, see _data/types.yaml for all avail
links:
  email: info@sparglab.org
  github: metu-sparg
  twitter: metusparg

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
